In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(3,18)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [8]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
np.arange(1,40,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36])

In [10]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,2,6)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [20]:
np.linspace(0,20,7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [21]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [22]:
np.random.rand(3,5)

array([[0.33826735, 0.08173142, 0.63006048, 0.18412618, 0.10407213],
       [0.50334008, 0.38826626, 0.56920426, 0.53457058, 0.99990935],
       [0.07480404, 0.25514882, 0.07472919, 0.24050254, 0.8241538 ]])

In [23]:
arr=np.random.randn(2,4)
arr

array([[ 0.88459721,  0.42246376, -2.64473474, -0.87353865],
       [ 1.3425399 ,  0.30168718,  1.36051158, -0.48463212]])

In [24]:
np.random.randint(2,100)

44

In [25]:
np.random.randint(20,56,100)

array([48, 21, 37, 45, 49, 33, 39, 44, 54, 23, 52, 50, 27, 54, 32, 30, 39,
       32, 44, 55, 20, 36, 28, 50, 39, 20, 39, 20, 28, 51, 55, 23, 25, 35,
       52, 49, 52, 45, 33, 41, 44, 25, 21, 36, 35, 24, 35, 32, 42, 42, 29,
       51, 26, 48, 20, 22, 36, 38, 39, 46, 28, 33, 39, 26, 40, 33, 41, 55,
       20, 55, 36, 50, 42, 46, 43, 23, 44, 41, 51, 32, 53, 30, 50, 20, 48,
       43, 23, 24, 51, 32, 52, 31, 26, 26, 38, 38, 41, 32, 50, 40])

In [26]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
rand_array=np.random.randint(0,10,50)
rand_array

array([1, 9, 5, 0, 4, 0, 9, 9, 1, 2, 4, 0, 7, 5, 1, 3, 5, 9, 9, 0, 9, 9,
       8, 0, 1, 3, 6, 5, 3, 3, 0, 5, 6, 7, 2, 4, 8, 3, 3, 0, 6, 3, 7, 1,
       9, 2, 5, 2, 6, 7])

In [29]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [31]:
rand_array.max()

9

In [32]:
rand_array.argmax()

1

In [34]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
a=np.random.rand(2,3)
a

array([[0.51896366, 0.58978813, 0.89486714],
       [0.265824  , 0.33830722, 0.10894721]])

In [37]:
a.T

array([[0.51896366, 0.265824  ],
       [0.58978813, 0.33830722],
       [0.89486714, 0.10894721]])

In [39]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
sample_array[0]

10

In [41]:
sample_array[2:5]

array([12, 13, 14])

In [42]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [43]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [45]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [46]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two Dimensional array

In [47]:
import numpy as np

In [48]:
sample_matrix=np.array([[50,20,1,23],[4,56,71,45],[60,19,24,15]])
sample_matrix

array([[50, 20,  1, 23],
       [ 4, 56, 71, 45],
       [60, 19, 24, 15]])

In [49]:
sample_matrix[1,2]

71

In [50]:
sample_matrix[2,:]

array([60, 19, 24, 15])

In [51]:
sample_matrix[2]

array([60, 19, 24, 15])

In [52]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [45, 71],
       [15, 24]])

### selection techniques

In [55]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [56]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [58]:
np.exp(sample_array) # exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [59]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [60]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [61]:
np.max(sample_array)

19

In [62]:
np.min(sample_array)

1

In [64]:
np.argmax(sample_array)

18

In [65]:
np.argmin(sample_array)

0

In [66]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [67]:
np.std(sample_array)

5.477225575051661

In [68]:
np.var(sample_array)

30.0

In [69]:
np.mean(sample_array)

10.0

In [70]:
array=np.random.randn(3,4)
array

array([[ 1.72019902, -1.59582239, -0.28674343, -0.93343875],
       [-0.19740357,  1.04700341, -0.40546544, -1.58825952],
       [ 1.45833672,  0.72769486, -0.29449632, -0.58850345]])

In [71]:
np.round(array,decimals=2)

array([[ 1.72, -1.6 , -0.29, -0.93],
       [-0.2 ,  1.05, -0.41, -1.59],
       [ 1.46,  0.73, -0.29, -0.59]])

In [72]:
sports=np.array(['golf','cricket','football','cricket'])
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')

### Pandas dataframe and indexing

In [73]:
### pandas

In [74]:
import pandas as pd
import numpy as np

In [75]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [76]:
sports1['football']

2

In [78]:
sports2=pd.Series([11,2,4,5],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     4
golf         5
dtype: int64

In [79]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           9.0
dtype: float64

In [80]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.324716  0.572646  0.227679  0.350670  0.598349
B  0.199626  0.691633  0.893691  0.655934  0.620441
C  0.112951  0.635104  0.100712  0.571122  0.913957
D  0.735792  0.045346  0.555707  0.976390  0.375133
E  0.481786  0.592009  0.426363  0.405380  0.414599
F  0.708236  0.262696  0.482539  0.630044  0.936800
G  0.717912  0.498099  0.947232  0.127727  0.415715
H  0.455551  0.757164  0.509103  0.535799  0.038238

In [81]:
df1["score1"]

A    0.324716
B    0.199626
C    0.112951
D    0.735792
E    0.481786
F    0.708236
G    0.717912
H    0.455551
Name: score1, dtype: float64

In [82]:
df1[["score1","score2","score3"]]

score1    score2    score3
A  0.324716  0.572646  0.227679
B  0.199626  0.691633  0.893691
C  0.112951  0.635104  0.100712
D  0.735792  0.045346  0.555707
E  0.481786  0.592009  0.426363
F  0.708236  0.262696  0.482539
G  0.717912  0.498099  0.947232
H  0.455551  0.757164  0.509103

In [83]:
df1['score6']=df1['score1']+df1['score2']
df1

score1    score2    score3    score4    score5    score6
A  0.324716  0.572646  0.227679  0.350670  0.598349  0.897362
B  0.199626  0.691633  0.893691  0.655934  0.620441  0.891259
C  0.112951  0.635104  0.100712  0.571122  0.913957  0.748055
D  0.735792  0.045346  0.555707  0.976390  0.375133  0.781138
E  0.481786  0.592009  0.426363  0.405380  0.414599  1.073795
F  0.708236  0.262696  0.482539  0.630044  0.936800  0.970932
G  0.717912  0.498099  0.947232  0.127727  0.415715  1.216011
H  0.455551  0.757164  0.509103  0.535799  0.038238  1.212715

In [84]:
df2={'ID':['100','101','150','160','200'],'Name':['priya','aishu','mercy','littu','lilly'],'profit':[20,35,50,62,100]}
df=pd.DataFrame(df2)
df

ID   Name  profit
0  100  priya      20
1  101  aishu      35
2  150  mercy      50
3  160  littu      62
4  200  lilly     100

In [85]:
df["ID"]

0    100
1    101
2    150
3    160
4    200
Name: ID, dtype: object

In [86]:
df[["ID","Name"]]

ID   Name
0  100  priya
1  101  aishu
2  150  mercy
3  160  littu
4  200  lilly

In [87]:
df=df.drop("ID",axis=1)
df

Name  profit
0  priya      20
1  aishu      35
2  mercy      50
3  littu      62
4  lilly     100

In [88]:
df.drop(3)

Name  profit
0  priya      20
1  aishu      35
2  mercy      50
4  lilly     100